"""
Central schema defining all tunable configuration fields for UI generation.
Each entry: dot_path, label, type, group, default, min, max, step, options, restart_required, description
Type: int, float, bool, str, choice, list_str
Group maps to top-level yaml sections for All tab grouping.
"""

SCHEMA = [
    # capture group
    dict(
        path="capture.target_fps",
        label="Target FPS (grab)",
        type="int",
        group="capture",
        default=30,
        min=10,
        max=240,
        step=1,
        description="How fast dxcam grabs frames into buffer. Higher = fresher frames, low CPU cost.",
    ),
    dict(
        path="capture.process_fps",
        label="Process FPS",
        type="int",
        group="capture",
        default=10,
        min=1,
        max=60,
        step=1,
        description="How many times per second to run YOLO+OCR+track. Main performance knob.",
    ),
    dict(
        path="capture.output_width",
        label="Output Width",
        type="int",
        group="capture",
        default=1280,
        min=640,
        max=2560,
        step=160,
        description="Resize width for inference. Lower = faster. Requires restart.",
        restart=True,
    ),
    dict(
        path="capture.monitor",
        label="Monitor Index",
        type="int",
        group="capture",
        default=0,
        min=0,
        max=3,
        step=1,
        description="0=primary monitor for dxcam. Requires restart.",
        restart=True,
    ),
    dict(
        path="capture.region",
        label="Region [l,t,w,h] or empty",
        type="str",
        group="capture",
        default="",
        description="Leave empty for full screen, or e.g. 0,0,1920,1080. Requires restart.",
        restart=True,
    ),
    # detector group
    dict(
        path="detector.model",
        label="Model Path",
        type="choice",
        group="detector",
        default="yolov8s-worldv2.pt",
        options=[
            "yolov8s-worldv2.pt",
            "yolov8s-world.pt",
            "yolo11n.pt",
            "yolo11s.pt",
            "yolo11m.pt",
            "yolov8n.pt",
        ],
        description="YOLO-World for zero-shot open vocab, or yolo11n after fine-tune. Requires restart.",
        restart=True,
    ),
    dict(
        path="detector.classes",
        label="Classes comma-separated",
        type="list_str",
        group="detector",
        default="character,person,enemy,player,health bar,notice,button,item,text,dialog,menu",
        description="Open-vocab classes for YOLO-World. Ignored for fine-tuned yolo11n unless you retrain.",
    ),
    dict(
        path="detector.conf",
        label="Confidence Threshold",
        type="float",
        group="detector",
        default=0.25,
        min=0.05,
        max=0.9,
        step=0.05,
        description="Higher = fewer false positives, fewer boxes to track.",
    ),
    dict(
        path="detector.iou",
        label="IoU NMS Threshold",
        type="float",
        group="detector",
        default=0.45,
        min=0.1,
        max=0.9,
        step=0.05,
    ),
    dict(
        path="detector.max_det",
        label="Max Detections",
        type="int",
        group="detector",
        default=100,
        min=10,
        max=300,
        step=10,
    ),
    dict(
        path="detector.device",
        label="Device",
        type="choice",
        group="detector",
        default="cuda",
        options=["cuda", "cpu"],
        description="cuda for NVIDIA GPU, cpu fallback. Requires restart.",
        restart=True,
    ),
    dict(
        path="detector.half",
        label="FP16 Half Precision",
        type="bool",
        group="detector",
        default=True,
        description="Faster on RTX GPU, disable if errors.",
    ),
    # tracker group
    dict(
        path="tracker.type",
        label="Tracker Type",
        type="choice",
        group="tracker",
        default="bytetrack",
        options=["bytetrack", "botsort"],
        description="ByteTrack is faster, BoT-SORT more robust ID switch handling.",
    ),
    dict(
        path="tracker.track_buffer",
        label="Track Buffer Frames",
        type="int",
        group="tracker",
        default=30,
        min=5,
        max=120,
        step=5,
        description="How long to keep lost tracks alive for re-ID.",
    ),
    # ocr group
    dict(
        path="ocr.enabled", label="OCR Enabled", type="bool", group="ocr", default=True
    ),
    dict(
        path="ocr.lang",
        label="OCR Language",
        type="choice",
        group="ocr",
        default="ch",
        options=["ch", "en", "ch_server", "en_server", "japan", "korean"],
        description="ch = Chinese+English mixed. Requires restart to reload models.",
        restart=True,
    ),
    dict(
        path="ocr.roi_only",
        label="OCR ROI Only",
        type="bool",
        group="ocr",
        default=True,
        description="True = OCR only inside detected text boxes ~8ms. False = full frame ~25ms but catches more.",
    ),
    dict(
        path="ocr.det_thresh",
        label="OCR Det Threshold",
        type="float",
        group="ocr",
        default=0.3,
        min=0.1,
        max=0.9,
        step=0.05,
    ),
    dict(
        path="ocr.rec_thresh",
        label="OCR Rec Threshold",
        type="float",
        group="ocr",
        default=0.5,
        min=0.1,
        max=0.9,
        step=0.05,
    ),
    dict(
        path="ocr.use_gpu",
        label="OCR Use GPU",
        type="bool",
        group="ocr",
        default=True,
        description="Requires onnxruntime-gpu installed. See check_gpu.py",
    ),
    dict(
        path="ocr.diff_threshold",
        label="Text Change Sensitivity",
        type="float",
        group="ocr",
        default=0.6,
        min=0.1,
        max=1.0,
        step=0.05,
        description="Higher = more sensitive to new text notices.",
    ),
    # vlm group
    dict(
        path="vlm.enabled",
        label="VLM Enabled",
        type="bool",
        group="vlm",
        default=False,
        description="Runs Ollama in background thread every N frames for semantic caption.",
    ),
    dict(
        path="vlm.provider",
        label="VLM Provider",
        type="choice",
        group="vlm",
        default="ollama",
        options=["ollama", "transformers"],
    ),
    dict(
        path="vlm.model",
        label="VLM Model",
        type="str",
        group="vlm",
        default="moondream:latest",
        description="Ollama model name e.g. moondream:latest or qwen2.5vl:3b",
    ),
    dict(
        path="vlm.interval",
        label="VLM Interval Frames",
        type="int",
        group="vlm",
        default=3,
        min=1,
        max=30,
        step=1,
    ),
    dict(
        path="vlm.prompt",
        label="VLM Prompt",
        type="str",
        group="vlm",
        default="Describe the game UI state in one short sentence. List visible characters, enemies, and any notice text.",
    ),
    # overlay group
    dict(
        path="overlay.show",
        label="Show Overlay Window",
        type="bool",
        group="overlay",
        default=True,
    ),
    dict(
        path="overlay.show_fps",
        label="Show FPS HUD",
        type="bool",
        group="overlay",
        default=True,
    ),
    dict(
        path="overlay.show_trails",
        label="Show Trails",
        type="bool",
        group="overlay",
        default=True,
    ),
    dict(
        path="overlay.show_ocr",
        label="Show OCR Boxes",
        type="bool",
        group="overlay",
        default=True,
    ),
    dict(
        path="overlay.show_labels",
        label="Show Labels",
        type="bool",
        group="overlay",
        default=True,
    ),
    dict(
        path="overlay.trail_length",
        label="Trail Length",
        type="int",
        group="overlay",
        default=15,
        min=5,
        max=60,
        step=5,
    ),
    # output group
    dict(
        path="output.save_dir",
        label="Save Directory",
        type="str",
        group="output",
        default="captures",
    ),
    dict(
        path="output.log_level",
        label="Log Level",
        type="choice",
        group="output",
        default="INFO",
        options=["DEBUG", "INFO", "WARNING", "ERROR"],
    ),
]

# Default custom pane selection - user can manage via UI Manage button, saved to ui_custom.json
DEFAULT_CUSTOM_SELECTION = [
    "capture.process_fps",
    "capture.output_width",
    "detector.conf",
    "detector.iou",
    "detector.device",
    "ocr.enabled",
    "ocr.lang",
    "ocr.roi_only",
    "overlay.show_trails",
    "vlm.enabled",
]
